
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvjfqefqrmgzwkhtknbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2amZxZWZxcm1nendraHRrbmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzU5NDksImV4cCI6MjA1OTc1MTk0OX0.2Tb29dHS4Gc3dL9KceXCc8UlRlLhg7U-m_gKFpVSL5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storageKey: 'portfolio-auth-token',
  },
  global: {
    headers: {
      'x-application-name': 'portfolio-website',
    },
  }
});

// Log creation of Supabase client
console.log("Supabase client initialized");
